version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app-deployment
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 45
  #     runas: ubuntu
