version: 0.2

env:
  parameter-store:
    DB_HOST: "/dev/database/host"
    DB_NAME: "/dev/database/db_name"
    DB_USER: "/dev/database/user"
    DB_PASSWORD: "/dev/database/password"

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - apt-get update
      - java -version
      - mvn -version 
      - echo $DB_HOST
      - echo $DB_NAME

  pre_build:
    commands:
      - echo Cleaning any previously compiled classes or created artifacts to ensure a fresh build...
      - mvn clean
      - echo Running Maven validate...
      - mvn validate
      - echo Compiling code...
      - mvn compile
      - echo Compiling test code...
      - mvn test-compile

  build:
    commands:
      - echo Running unit tests...
      - mvn test
      - echo Packaging compiled code into binary...
      - mvn package

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Verifying packaged binary...
      - mvn verify

      - echo Listing files in target directory..
      - ls -alh target
      - ls -alh scripts

artifacts:
  files:
    - '**/*'
  discard-paths: no
